// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyAPI.Data;

#nullable disable

namespace PharmacyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409060924_FixSeedData")]
    partial class FixSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyAPI.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Packaging")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("bit");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Pain Relief",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Effective pain reliever and fever reducer. Suitable for headaches, muscle aches, and cold symptoms.",
                            Dosage = "1-2 tablets every 4-6 hours",
                            ImageUrl = "/images/medicines/paracetamol.jpg",
                            IsAvailable = true,
                            Manufacturer = "Sun Pharma",
                            Name = "Paracetamol 500mg",
                            Packaging = "Strip of 10 tablets",
                            Price = 35.00m,
                            RequiresPrescription = false,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 2,
                            Category = "Pain Relief",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-steroidal anti-inflammatory drug for pain, fever, and inflammation.",
                            Dosage = "1 tablet every 6-8 hours",
                            ImageUrl = "/images/medicines/ibuprofen.jpg",
                            IsAvailable = true,
                            Manufacturer = "Cipla",
                            Name = "Ibuprofen 400mg",
                            Packaging = "Strip of 10 tablets",
                            Price = 45.00m,
                            RequiresPrescription = false,
                            StockQuantity = 350
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pain Relief",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Prescription-grade anti-inflammatory for moderate to severe pain relief.",
                            Dosage = "1 tablet twice daily",
                            ImageUrl = "/images/medicines/diclofenac.jpg",
                            IsAvailable = true,
                            Manufacturer = "Novartis",
                            Name = "Diclofenac 50mg",
                            Packaging = "Strip of 10 tablets",
                            Price = 65.00m,
                            RequiresPrescription = true,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 4,
                            Category = "Antibiotics",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Broad-spectrum antibiotic for bacterial infections including throat, ear, and urinary infections.",
                            Dosage = "1 capsule every 8 hours",
                            ImageUrl = "/images/medicines/amoxicillin.jpg",
                            IsAvailable = true,
                            Manufacturer = "Dr. Reddy's",
                            Name = "Amoxicillin 500mg",
                            Packaging = "Strip of 10 capsules",
                            Price = 120.00m,
                            RequiresPrescription = true,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 5,
                            Category = "Antibiotics",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Macrolide antibiotic for respiratory, skin, and ear infections.",
                            Dosage = "1 tablet daily for 3-5 days",
                            ImageUrl = "/images/medicines/azithromycin.jpg",
                            IsAvailable = true,
                            Manufacturer = "Zydus",
                            Name = "Azithromycin 250mg",
                            Packaging = "Strip of 6 tablets",
                            Price = 95.00m,
                            RequiresPrescription = true,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 6,
                            Category = "Antibiotics",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fluoroquinolone antibiotic for urinary tract and respiratory infections.",
                            Dosage = "1 tablet every 12 hours",
                            ImageUrl = "/images/medicines/ciprofloxacin.jpg",
                            IsAvailable = true,
                            Manufacturer = "Lupin",
                            Name = "Ciprofloxacin 500mg",
                            Packaging = "Strip of 10 tablets",
                            Price = 85.00m,
                            RequiresPrescription = true,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 7,
                            Category = "Vitamins & Supplements",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-potency vitamin C supplement for immunity support and antioxidant protection.",
                            Dosage = "1 tablet daily",
                            ImageUrl = "/images/medicines/vitaminc.jpg",
                            IsAvailable = true,
                            Manufacturer = "HealthKart",
                            Name = "Vitamin C 1000mg",
                            Packaging = "Bottle of 60 tablets",
                            Price = 250.00m,
                            RequiresPrescription = false,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 8,
                            Category = "Vitamins & Supplements",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Weekly vitamin D3 supplement for bone health and calcium absorption.",
                            Dosage = "1 capsule weekly",
                            ImageUrl = "/images/medicines/vitamind.jpg",
                            IsAvailable = true,
                            Manufacturer = "Sun Pharma",
                            Name = "Vitamin D3 60000 IU",
                            Packaging = "Strip of 8 capsules",
                            Price = 180.00m,
                            RequiresPrescription = false,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 9,
                            Category = "Vitamins & Supplements",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete daily multivitamin with minerals for overall health and wellness.",
                            Dosage = "1 tablet daily after meals",
                            ImageUrl = "/images/medicines/multivitamin.jpg",
                            IsAvailable = true,
                            Manufacturer = "Centrum",
                            Name = "Multivitamin Complex",
                            Packaging = "Bottle of 90 tablets",
                            Price = 350.00m,
                            RequiresPrescription = false,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 10,
                            Category = "Vitamins & Supplements",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium fish oil capsules rich in EPA and DHA for heart and brain health.",
                            Dosage = "1 capsule twice daily",
                            ImageUrl = "/images/medicines/omega3.jpg",
                            IsAvailable = true,
                            Manufacturer = "HealthVit",
                            Name = "Omega-3 Fish Oil",
                            Packaging = "Bottle of 60 softgels",
                            Price = 450.00m,
                            RequiresPrescription = false,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 11,
                            Category = "Digestive Health",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Proton pump inhibitor for acid reflux, heartburn, and gastric ulcers.",
                            Dosage = "1 capsule before breakfast",
                            ImageUrl = "/images/medicines/omeprazole.jpg",
                            IsAvailable = true,
                            Manufacturer = "Cipla",
                            Name = "Omeprazole 20mg",
                            Packaging = "Strip of 15 capsules",
                            Price = 75.00m,
                            RequiresPrescription = false,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 12,
                            Category = "Digestive Health",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Anti-nausea medication for relief of nausea, vomiting, and bloating.",
                            Dosage = "1 tablet before meals",
                            ImageUrl = "/images/medicines/domperidone.jpg",
                            IsAvailable = true,
                            Manufacturer = "Torrent Pharma",
                            Name = "Domperidone 10mg",
                            Packaging = "Strip of 10 tablets",
                            Price = 55.00m,
                            RequiresPrescription = false,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 13,
                            Category = "Allergy & Cold",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Antihistamine for allergic rhinitis, hay fever, and skin allergies.",
                            Dosage = "1 tablet daily",
                            ImageUrl = "/images/medicines/cetirizine.jpg",
                            IsAvailable = true,
                            Manufacturer = "Dr. Reddy's",
                            Name = "Cetirizine 10mg",
                            Packaging = "Strip of 10 tablets",
                            Price = 25.00m,
                            RequiresPrescription = false,
                            StockQuantity = 600
                        },
                        new
                        {
                            Id = 14,
                            Category = "Allergy & Cold",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Leukotriene receptor antagonist for asthma and allergic rhinitis.",
                            Dosage = "1 tablet daily at bedtime",
                            ImageUrl = "/images/medicines/montelukast.jpg",
                            IsAvailable = true,
                            Manufacturer = "Sun Pharma",
                            Name = "Montelukast 10mg",
                            Packaging = "Strip of 10 tablets",
                            Price = 140.00m,
                            RequiresPrescription = true,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 15,
                            Category = "Allergy & Cold",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Effective cough suppressant for dry, tickly cough relief.",
                            Dosage = "10ml every 4-6 hours",
                            ImageUrl = "/images/medicines/coughsyrup.jpg",
                            IsAvailable = true,
                            Manufacturer = "Dabur",
                            Name = "Cough Syrup (Dextromethorphan)",
                            Packaging = "Bottle of 100ml",
                            Price = 85.00m,
                            RequiresPrescription = false,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 16,
                            Category = "Skin Care",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Antifungal cream for athlete's foot, ringworm, and fungal skin infections.",
                            Dosage = "Apply twice daily",
                            ImageUrl = "/images/medicines/clotrimazole.jpg",
                            IsAvailable = true,
                            Manufacturer = "Glenmark",
                            Name = "Clotrimazole Cream 1%",
                            Packaging = "Tube of 20g",
                            Price = 95.00m,
                            RequiresPrescription = false,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 17,
                            Category = "Skin Care",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Topical corticosteroid for eczema, dermatitis, and inflammatory skin conditions.",
                            Dosage = "Apply thin layer twice daily",
                            ImageUrl = "/images/medicines/betamethasone.jpg",
                            IsAvailable = true,
                            Manufacturer = "GSK",
                            Name = "Betamethasone Cream 0.1%",
                            Packaging = "Tube of 15g",
                            Price = 110.00m,
                            RequiresPrescription = true,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 18,
                            Category = "Diabetes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First-line medication for type 2 diabetes mellitus management.",
                            Dosage = "1 tablet twice daily with meals",
                            ImageUrl = "/images/medicines/metformin.jpg",
                            IsAvailable = true,
                            Manufacturer = "USV",
                            Name = "Metformin 500mg",
                            Packaging = "Strip of 10 tablets",
                            Price = 45.00m,
                            RequiresPrescription = true,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 19,
                            Category = "Heart & BP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Calcium channel blocker for high blood pressure and chest pain (angina).",
                            Dosage = "1 tablet daily",
                            ImageUrl = "/images/medicines/amlodipine.jpg",
                            IsAvailable = true,
                            Manufacturer = "Pfizer",
                            Name = "Amlodipine 5mg",
                            Packaging = "Strip of 10 tablets",
                            Price = 55.00m,
                            RequiresPrescription = true,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 20,
                            Category = "Heart & BP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Low-dose aspirin for cardiovascular protection and blood thinning.",
                            Dosage = "1 tablet daily",
                            ImageUrl = "/images/medicines/aspirin.jpg",
                            IsAvailable = true,
                            Manufacturer = "Bayer",
                            Name = "Aspirin 75mg",
                            Packaging = "Strip of 14 tablets",
                            Price = 30.00m,
                            RequiresPrescription = false,
                            StockQuantity = 500
                        });
                });

            modelBuilder.Entity("PharmacyAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PharmacyAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PharmacyAPI.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PharmacyAPI.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("PharmacyAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Admin Street, Healthcare City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@pharmacy.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$edR8FoCTXi0E7SB3Je32Ze9A6DXfQCPxZipT2hxFVuIcGNftigMMa",
                            Phone = "9876543210",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Pharma Lane, Healthcare City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pharmacist@pharmacy.com",
                            Name = "Pharmacist User",
                            PasswordHash = "$2a$11$0E5s7kw4UaiNeZ0mm0SWnOP4gsc82GGq.6PA6gvWZ.UjzIuvcCARS",
                            Phone = "9876543211",
                            Role = "Pharmacist"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Customer Road, Wellness Town",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            Name = "John Customer",
                            PasswordHash = "$2a$11$Mj0XmcxisGbHWG8OShMhzuQPNzZ6ZWr1wKeHdw.nii2.CNFkBStnq",
                            Phone = "9876543212",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("PharmacyAPI.Models.Order", b =>
                {
                    b.HasOne("PharmacyAPI.Models.Prescription", "Prescription")
                        .WithMany("Orders")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PharmacyAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prescription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyAPI.Models.OrderItem", b =>
                {
                    b.HasOne("PharmacyAPI.Models.Medicine", "Medicine")
                        .WithMany("OrderItems")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PharmacyAPI.Models.Payment", b =>
                {
                    b.HasOne("PharmacyAPI.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("PharmacyAPI.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PharmacyAPI.Models.Prescription", b =>
                {
                    b.HasOne("PharmacyAPI.Models.User", "User")
                        .WithMany("Prescriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyAPI.Models.Medicine", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PharmacyAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("PharmacyAPI.Models.Prescription", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PharmacyAPI.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
